export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REFRESH_SEARCH_FIELD = 'REFRESH_SEARCH_FIELD';
export const ADD_ROBOT = 'ADD_ROBOT';
export const CLEAR_ROBOT = 'CLEAR_ROBOT';
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAIL = 'REQUEST_ROBOTS_FAIL';
